In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [4]:
#Q.1
list_

['1', '2', '3', '4', '5']

In [7]:
array_list.dtype

dtype('<U1')

In [ ]:
#Q.2


In [14]:
list_

['1', '2', '3', '4', '5']

In [37]:
arr =np.array(list_)

In [39]:
arr.dtype

dtype('<U1')

In [44]:
arr1 =np.array(array_list)

In [45]:
arr1.dtype

dtype('<U1')

In [ ]:
#Q.3


In [46]:
array_list = np.array(object = list_, dtype = int)

In [47]:
array_list

array([1, 2, 3, 4, 5])

In [48]:
array_list.dtype

dtype('int64')

In [49]:
#Q.4

In [50]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [51]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [52]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
# i
num_array.shape

(2, 3)

In [55]:
# ii
num_array.size

6

In [69]:
#Q.5
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [1]:
#Q.6
import numpy as np

In [21]:
arr1 = np.array([1,1,1,1,1,(5,5)])

/tmp/ipykernel_196/1254073723.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr1 = np.array([1,1,1,1,1,(5,5)])


In [22]:
arr1

array([1, 1, 1, 1, 1, (5, 5)], dtype=object)